### ISSUE TITLE
单行模式下用pickerView选日期,会让上面日历中的红色选中状态偏离日期

### ISSUE THREAD

**Issue by Lafree317** [unixzii/Daysquare#1]
单行模式下用pickerView选日期,会让上面日历中的红色选中状态偏离日期
![2016-06-20 6 29 27](https://cloud.githubusercontent.com/assets/13520567/16191054/f60245ac-3714-11e6-8761-e5b8f9688f85.png)
![2016-06-20 6 29 35](https://cloud.githubusercontent.com/assets/13520567/16191061/fbd23e9c-3714-11e6-990b-66665571b8df.png)

这个库很不错,谢谢

**Comment by unixzii** [comment]
这点在设计时没有考虑到，我会尽快修复。现阶段使用时尽量避免单行模式下外部修改日期吧。

**Comment by unixzii** [comment]
现在已经修复这个 Bug 了，感谢支持。
