### ISSUE TITLE
cocopods problem

### ISSUE THREAD

**Issue by lee727n** [unixzii/Daysquare#6]
use this instruction  pod 'Daysquare', :git => 'https://github.com/unixzii/Daysquare.git'
the result is
[!] Unable to satisfy the following requirements:

- `Daysquare (from `https://github.com/unixzii/Daysquare.git`)` required by `Podfile`

Specs satisfying the `Daysquare (from `https://github.com/unixzii/Daysquare.git`)` dependency were found, but they required a higher minimum deployment target.
are you sure your pod command is right?

**Comment by altncmd** [comment]
I got this problem too

**Comment by altncmd** [comment]
it is a platform version problem:
<img width="586" alt="jietu20171016-092220" src="https://user-images.githubusercontent.com/22466729/31592580-8e60e244-b253-11e7-8977-68a6505d8d7c.png">

**Comment by unixzii** [comment]
That's not a bug. The library used `UIStackView` to build up UIs, which is only shipped with iOS 9.
